import gql from 'graphql-tag';

export interface PostPagination {
    items: Post[];
    hasNext?: boolean;
    params?: any; // queries args
}

export interface Post {
    text: string;

    owner?: string; // autogenerated
    id?: string; // autogenerated
    createdAt?: Date; // autogenerated
    updatedAt?: Date; // autogenerated

    replyToId?: string;
    parentId?: string;
    sensitive?: boolean;
    visibility?: string;
    spoilerText?: string;
    reply?: boolean;
    language?: string;
    editedAt?: Date;
    reactions?: number;
    attachments?: string[];
}

export const PostFragment = gql`
    fragment PostFragment on Post {
        id
        owner
        text
        replyToId
        parentId
        sensitive
        visibility
        spoilerText
        reply
        language
        editedAt
        reactions
        attachments
        createdAt
        updatedAt
    }
`;

export const PostPaginationFragment = gql`
    fragment PostPaginationFragment on PostPagination {
        items {
            ...PostFragment
        }
        hasNext
        params
    }
    ${PostFragment}
`;
