import gql from 'graphql-tag';

export interface Post {
    accountId: string;
    text: string;

    id?: string; // autogenerated
    createdAt: Date; // autogenerated
    updatedAt: Date; // autogenerated

    replyToId: string;
    parentId?: string;
    sensitive?: boolean;
    visibility?: string;
    spoilerText?: string;
    reply?: boolean;
    language?: string;
    editedAt?: Date;
    reactions?: number;
    attachments?: string[];
}

export const PostFragment = gql`
    fragment PostFragment on Post {
        id
        accountId
        text
        replyToId
        parentId
        sensitive
        visibility
        spoilerText
        reply
        language
        editedAt
        reactions
        attachments
        createdAt
        updatedAt
    }
`;
